site_name: site nav
site_url: https://mkdocs-multisite-test.kratapps.com

# Theme configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: custom
  features:
    - navigation.tabs

# Navigation configuration
nav:
  - Site 1: site1/
  - Site 2: site2/

